language: node_js
os: linux
node_js:
  - 'stable'
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
cache:
  directories:
    - node_modules
script:
  - npm run deploy
